export enum WebhookResponseStatus {
  ACCEPTED = 'ACCEPTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}

export enum RejectionReason {
  CARD_NOT_FOUND = 'CARD_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
  MONTHLY_LIMIT_EXCEEDED = 'MONTHLY_LIMIT_EXCEEDED',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST'
}
